ontologies:
  source:
    - url: 'https://spec.edmcouncil.org/auto/ontology/MetadataAUTO/'
    - url: 'https://spec.edmcouncil.org/auto/ontology/AboutAUTODev/'
  catalog_path:
    - ontologies/catalog-v001.xml
  module_ignore_pattern:
    - '^(About|Metadata|Load).*'
    - 'http.*(About|Metadata).*'
  module_class_iri: 'http://www.omg.org/techprocess/ab/SpecificationMetadata/Module'